### ISSUE TITLE
Thunderbird for e-mail

### ISSUE THREAD

**Issue by mbetrifork** [hcnp/trifork-dell-ubuntu#1]
Might want to include instructions for using Thunderbird as it has matured lately and is - as far as I am aware, the only native client to support S/MIME (signed and/or encrypted mail) on Ubuntu. Encrypted mail is relevant.

Also might want to include instructions for simply using the Outlook Web App (https://webmail.trifork.com/owa/) as many prefer the simplicity of that over a dedicated client.

Finally Blue Mail is a really nice third party option that also works on mobile. One-click setup for Exchange servers and a sleek, modern appearance.

**Comment by hcnp** [comment]
Evolution also supports S/MIME and GPG cf. [Mail encryption and certificates](https://help.gnome.org/users/evolution/stable/mail-encryption.html.en)

Sure. I think we can link to Thunderbird as an alternative, but I just had a look. It only supports IMAP without extensions and no calendar support without extensions.

How do you have it configured? If you use extensions which do you use?

Thunderbird configured [Owl for Exchange](https://addons.thunderbird.net/en-US/thunderbird/addon/owl-for-exchange), but that's a paid option. And for calendar I found [Provider for Exchange ActiveSync](https://addons.thunderbird.net/en-US/thunderbird/addon/eas-4-tbsync/), but ActiveSync should not be enabled as it is a security risk/does not support MFA/"Modern Authentication" cf. [Enabling Modern Auth in Exchange on-premises](https://learn.microsoft.com/en-us/exchange/plan-and-deploy/post-installation-tasks/enable-modern-auth-in-exchange-server-on-premises?view=exchserver-2019) which should be enabled for best practice security.

**Comment by hcnp** [comment]
I've added a section with "Other clients": https://github.com/hcnp/trifork-dell-ubuntu?tab=readme-ov-file#other-clients
